name: typescript
on:
  pull_request:
    branches: [main, staging]
  push:
    branches: [main, staging]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tsc
        run: tsc --noEmit --incremental
